### ISSUE TITLE
Error in build 32 bit version utils

### ISSUE THREAD

**Issue by blackeangel** [sekaiacg/erofs-utils#17]
When building with the 32-bit version of the utility, symlinks do not correctly point to the objects they link to. On the 64-bit version, SAR also breaks in the root of the image.
![Screenshot_20230925-193522](https://github.com/sekaiacg/erofs-utils/assets/20953770/646a7c82-9e87-4271-8112-5f2d4309a62b)
![Screenshot_20230925-215853](https://github.com/sekaiacg/erofs-utils/assets/20953770/2e277444-74c7-4985-a069-f5f196019fe7)

But version mkfs.erofs 1.4 work normally.
This error on versions 1.6+

**Comment by sekaiacg** [comment]
I used the latest build test and it didn't produce any errors.
```
lrwxrwxrwx  1 sekaiacg sekaiacg  11 2009年 1月 1日 cache -> /data/cache
dr-xr-xr-x  2 sekaiacg sekaiacg  40 2009年 1月 1日 config
drwxr-xr-x  2 sekaiacg sekaiacg  40 2009年 1月 1日 cust
lrwxrwxrwx  1 sekaiacg sekaiacg  17 2009年 1月 1日 d -> /sys/kernel/debug
drwxr-x--x  2 sekaiacg sekaiacg  40 2009年 1月 1日 data
drwxr-xr-x  2 sekaiacg sekaiacg  40 2009年 1月 1日 data_mirror
drwxr-xr-x  2 sekaiacg sekaiacg  40 2009年 1月 1日 debug_ramdisk
drwxr-xr-x  2 sekaiacg sekaiacg  40 2009年 1月 1日 dev
lrwxrwxrwx  1 sekaiacg sekaiacg  11 2009年 1月 1日 etc -> /system/etc
lrwxrwxrwx  1 sekaiacg sekaiacg  16 2009年 1月 1日 init -> /system/bin/init
```

**Comment by sekaiacg** [comment]
Please provide your image file for debugging

**Comment by romanovj** [comment]
@blackeangel check configure

`--with-selinux          enable and build with selinux support [default=no]`

**Comment by blackeangel** [comment]
> > > Please provide your image file for debugging
> > 
> > 
> > When using binary files compiled by you for Android (arm, arm64) mkfs.erofs, when building the folder with options:
> > `mkfs.erofs -zlz4hc,1 -T 1230768000 -U ab0b1e4a-4e6a-5650-8c75-2b0bf13ee5d4 --mount-point=/system_a --fs-config-file=./config/system_a/system_a_fs_config --file-contexts= ./config/system_a/system_a_file_contexts $outdir/system_a.new.img ./system_a`
> > and subsequent disassembly, symlinks point to non-existent objects, that is, they become broken:
> > `./sdcard -> /storage/self/primaryject_r:rootfs ./system/app/MiuiBluetooth/lib/arm64/libaivsopus.so -> /system/lib64/libaivsopus.sosystem ./system/app/MiuiBluetooth/lib/arm64/libjlspeex.so -> /system/lib64/libjlspeex.so:system ./system/app/MiuiBluetooth/lib/arm64/libxm_bluetooth.so -> /system/lib64/libxm_bluetooth.soem ./d -> /sys/kernel/debugu:object_r:rootfs and other` If you use a binary file from the Android 13 64 bit firmware, then the symlinks turn out normal and the files have contexts. If you collect source codes in Termux from an official source or from an AOSP source, then the symlinks are correct, but there are no contexts for the files, since the compiled binary file does not have the options: --fs-config-file --file-contexts.
> > Tested on system.img and vendor.img images with both broken links. Do you still need an image or not?
> 
> system.img is the original image. system_mk.img is an image that is repackaged using mkfs.erofs after being extracted by extract.erofs. system_mk is the result of extracting system_mk.img again. No abnormalities were found. `./mkfs.erofs -zlz4 --mount-point=/system --product-out=./ --fs-config-file=./config/system_fs_config --file-contexts=./config/system_file_contexts system_mk.img ./system` ![image](https://user-images.githubusercontent.com/33929605/270607747-b087cb4f-d9ff-4309-90ae-cd711e037fbf.png)

Rename system.img, for example, to system_a.img, then unpack, build and unpack again, and then the links will break.
If the image name is system.img, then they don’t seem to break.

**Comment by romanovj** [comment]
which device has mountpoint /system_a ?

**Comment by sekaiacg** [comment]
@blackeangel 
**Unable to reproduce, please check your operating environment or other issues.**
![image](https://github.com/sekaiacg/erofs-utils/assets/33929605/e54e399c-566c-4488-8cd8-590c77d2f9f2)

**Comment by blackeangel** [comment]
Please show me a complete listing of your actions, starting with downloading your binary from GitHub to an Android device in the /data/adb/test folder, unpacking, building and unpacking again.
Full listing please.
The error is somewhere nearby.

**Comment by sekaiacg** [comment]
You can try the latest linux aarch64 version in CI.
