### ISSUE TITLE
解包bug

### ISSUE THREAD

**Issue by EluneAdore** [sekaiacg/erofs-utils#18]
extract.erofs.exe每次在多个erofs镜像解包到odm.img必报错，日志在附件里，单独解包odm.img则无报错。
PS：windows11，extract.erofs.exe为最新的CI版（cygwin）
        `extract.erofs -x -f -i images/odm.img -o erofs/system`
[exception.log](https://github.com/sekaiacg/erofs-utils/files/12788003/exception.log)

**Comment by sekaiacg** [comment]
"extract.erofs.exe每次在多个erofs镜像解包到odm.img必报错"
这句话虽然是中文，但是我看不懂

**Comment by sekaiacg** [comment]
如果你想提取多个同名img，请使用-o指定不同的输出目录

**Comment by EluneAdore** [comment]
> "extract.erofs.exe每次在多个erofs镜像解包到odm.img必报错" 这句话虽然是中文，但是我看不懂

我把如下命令写到bat里了，每次处理到odm.img就报错。

`extract.erofs -x -f -i images/product.img -o erofs/system
extract.erofs -x -f -i images/system.img -o erofs
extract.erofs -x -f -i images/odm.img -o erofs/system
extract.erofs -x -f -i images/vendor.img -o erofs/system
extract.erofs -x -f -i images/system_ext.img -o erofs/system
extract.erofs -x -f -i images/my_bigball.img -o erofs/system
extract.erofs -x -f -i images/my_carrier.img -o erofs/system
extract.erofs -x -f -i images/my_engineering.img -o erofs/system
extract.erofs -x -f -i images/my_heytap.img -o erofs/system
extract.erofs -x -f -i images/my_manifest.img -o erofs/system
extract.erofs -x -f -i images/my_product.img -o erofs/system
extract.erofs -x -f -i images/my_region.img -o erofs/system
extract.erofs -x -f -i images/my_stock.img -o erofs/system`

但我单独执行如下命令则无报错

`extract.erofs -x -f -i images/odm.img -o erofs/system`

**Comment by sekaiacg** [comment]
> > "extract.erofs.exe每次在多个erofs镜像解包到odm.img必报错" 这句话虽然是中文，但是我看不懂
> 
> 我把如下命令写到bat里了，每次处理到odm.img就报错。
> 
> `extract.erofs -x -f -i images/product.img -o erofs/system extract.erofs -x -f -i images/system.img -o erofs extract.erofs -x -f -i images/odm.img -o erofs/system extract.erofs -x -f -i images/vendor.img -o erofs/system extract.erofs -x -f -i images/system_ext.img -o erofs/system extract.erofs -x -f -i images/my_bigball.img -o erofs/system extract.erofs -x -f -i images/my_carrier.img -o erofs/system extract.erofs -x -f -i images/my_engineering.img -o erofs/system extract.erofs -x -f -i images/my_heytap.img -o erofs/system extract.erofs -x -f -i images/my_manifest.img -o erofs/system extract.erofs -x -f -i images/my_product.img -o erofs/system extract.erofs -x -f -i images/my_region.img -o erofs/system extract.erofs -x -f -i images/my_stock.img -o erofs/system`
> 
> 但我单独执行如下命令则无报错
> 
> `extract.erofs -x -f -i images/odm.img -o erofs/system`

https://github.com/sekaiacg/erofs-utils/issues/18#issuecomment-1744226630

**Comment by sekaiacg** [comment]
**bug：**提供了-f参数，创建dir时出现错误并没有强制覆盖。
你的脚本将多个img提取到同一个文件夹触发了这个bug。
有一些dir是链接(link)，当链接失效时这个路径实际上并不存在，如果没有强制覆盖，无法真正的创建dir。
请尽量避免这样的操作。
尝试最新ci：
https://github.com/sekaiacg/erofs-utils/actions/runs/6389533569

**Comment by EluneAdore** [comment]
好的，我解包到默认路径，则没有报错了，感谢！！！
