### ISSUE TITLE
macOS sonoma打包镜像错误

### ISSUE THREAD

**Issue by tosasitill** [sekaiacg/erofs-utils#20]
```
mkfs.erofs 1.7-gce362738
loaded 1769 fs_config entries
<E> erofs: failed to build shared xattrs: [Error 96] No message available on STREAM
<E> erofs: 	Could not format the device : [Error 96] No message available on STREAM
```
使用的命令是
```
mkfs.erofs --mount-point ${pname} --fs-config-file build/portrom/config/${pname}_fs_config --file-contexts build/portrom/config/${pname}_file_contexts build/portrom/images/${pname}.img build/portrom/images/${pname}
```
实测其他分区按照此命令都可以正常打包，唯有这个'product.img'无法打包
使用的是最新Release版本的Darwin-X64，系统版本是14.1.1 (23B81)

这里是分解出来的configs:[product_fs:file_config.zip](https://github.com/sekaiacg/erofs-utils/files/13649719/product_fs.file_config.zip)

**Comment by sekaiacg** [comment]
请在参数中添加开启调试，获取更多log

**Comment by sekaiacg** [comment]
请提供一下rom链接

**Comment by tosasitill** [comment]
这里是链接：[我](https://ultimateota.d.miui.com/OS1.0.3.0.UMCCNXM/miui_FUXI_OS1.0.3.0.UMCCNXM_e0bcc18a25_14.0.zip?t=1702396524&s=2f0d2130214149e8abed3a33b8cbc1d5)
我现在尝试使用action的版本

**Comment by sekaiacg** [comment]
你提供的product_fs.file_config.zip 中缺少files_context
请确认你对files_context的修改是正确的。
我这没有macos的设备，没办法进一步判断。
你可以尝试以下方法验证：
使用extract.erofs提取后不要进行任何修改，尝试使用product_fs_options中提供的参数能否打包
`./mkfs.erofs -zlz4hc,1 -T 1230768000 -U 13729282-2c7c-536e-a5a3-17c9978eb0c2 --mount-point=/product --fs-config-file=./config/product_fs_config --file-contexts=./config/product_file_contexts product_repack.img ./product`

**Comment by sekaiacg** [comment]
添加-d9参数显示更多log，请上传l.log
`./mkfs.erofs -d9 -zlz4hc,1 -T 1230768000 -U 13729282-2c7c-536e-a5a3-17c9978eb0c2 --mount-point=/product --fs-config-file=./config/product_fs_config --file-contexts=./config/product_file_contexts product_repack.img ./product 2>&1 | tee l.log`

**Comment by tosasitill** [comment]
打包成功了 应该是我的指令出现了问题 麻烦你了
