### ISSUE TITLE
fuse.erofs not working

### ISSUE THREAD

**Issue by BlackMesa123** [sekaiacg/erofs-utils#21]
fuse.erofs built with the latest upstream tree at the time of writing (bd0c536c59cbca66e91ef4f405e2ae52cff8bf67) isn't working.
```console
❯ fuse.erofs --dbglevel=9 -d odm.img tmp_out
erofsfuse 1.7.1-gce4d890c
FUSE library version: 3.16.2
<W> erofs: odm.img mounted on tmp_out with offset 0
```
Tried both building myself and the latest workflow artifacts (https://github.com/sekaiacg/erofs-utils/actions/runs/7541502900).

**Comment by sekaiacg** [comment]
[erofs-utils: fuse: support FUSE 2/3 multi-threading](https://github.com/erofs/erofs-utils/commit/ce4d890cf77a67546b87cd2671dab53a6f317b31)
There is a problem when determining the libfuse version.
I have almost adapted the judgment method when compiling with libfuse.

**Comment by sekaiacg** [comment]
Please try later::https://github.com/sekaiacg/erofs-utils/actions/runs/7556709082
Before doing so, run **unmount tmp_out** to uninstall the corrupted mount directory.

**Comment by BlackMesa123** [comment]
Works again, thank you for addressing this issue.
