### ISSUE TITLE
Please upload cygwin packed.

### ISSUE THREAD

**Issue by seci20** [sekaiacg/erofs-utils#22]
Can you upload your cygwin package? Even though I installed the packages, incompatibility occurs.

**Comment by sekaiacg** [comment]
Please download the CI automatically built release here:
https://github.com/sekaiacg/erofs-utils/releases

Please click here for the specific configuration of cygwin:
https://github.com/sekaiacg/erofs-utils/blob/6318f79ab778f65982d8e6044bcfc48245a4b177/.github/workflows/build-erofs-utils.yml#L272

**Comment by seci20** [comment]
$ ./build_cygwin.sh

-- The C compiler identification is Clang 18.1.5 with GNU-like command-line
-- The CXX compiler identification is Clang 18.1.5 with GNU-like command-line
-- Detecting C compiler ABI info
CMake Error:
  Running

   '/usr/bin/ninja.exe' '-C' '/home/mesut/erofs/out/CMakeFiles/CMakeScratch/TryCompile-Z8WXCm' '-t' 'recompact'

  failed with:

   ninja: fatal: chdir to '/home/mesut/erofs/out/CMakeFiles/CMakeScratch/TryCompile-Z8WXCm' - No such file or directory



CMake Error:
  Running

   '/usr/bin/ninja.exe' '-C' '/home/mesut/erofs/out/CMakeFiles/CMakeScratch/TryCompile-Z8WXCm' '-t' 'restat' 'build.ninja'

  failed with:

   ninja: fatal: chdir to '/home/mesut/erofs/out/CMakeFiles/CMakeScratch/TryCompile-Z8WXCm' - No such file or directory



CMake Error at /usr/share/cmake-3.28.3/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  /usr/share/cmake-3.28.3/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
ninja: error: loading 'build.ninja': The system cannot find the file specified.

ninja: Entering directory `./out'
error

whats problem ?

**Comment by sekaiacg** [comment]
> $ ./build_cygwin.sh
> 
> -- The C compiler identification is Clang 18.1.5 with GNU-like command-line -- The CXX compiler identification is Clang 18.1.5 with GNU-like command-line -- Detecting C compiler ABI info CMake Error: Running
> 
> '/usr/bin/ninja.exe' '-C' '/home/mesut/erofs/out/CMakeFiles/CMakeScratch/TryCompile-Z8WXCm' '-t' 'recompact'
> 
> failed with:
> 
> ninja: fatal: chdir to '/home/mesut/erofs/out/CMakeFiles/CMakeScratch/TryCompile-Z8WXCm' - No such file or directory
> 
> CMake Error: Running
> 
> '/usr/bin/ninja.exe' '-C' '/home/mesut/erofs/out/CMakeFiles/CMakeScratch/TryCompile-Z8WXCm' '-t' 'restat' 'build.ninja'
> 
> failed with:
> 
> ninja: fatal: chdir to '/home/mesut/erofs/out/CMakeFiles/CMakeScratch/TryCompile-Z8WXCm' - No such file or directory
> 
> CMake Error at /usr/share/cmake-3.28.3/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile): Failed to generate test project build system. Call Stack (most recent call first): /usr/share/cmake-3.28.3/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI) CMakeLists.txt:2 (project)
> 
> -- Configuring incomplete, errors occurred! ninja: error: loading 'build.ninja': The system cannot find the file specified.
> 
> ninja: Entering directory `./out' error
> 
> whats problem ?

I don't use windows, cygwin is supported by others.
@affggh

**Comment by affggh** [comment]
> $ ./build_cygwin.sh
> 
> -- The C compiler identification is Clang 18.1.5 with GNU-like command-line -- The CXX compiler identification is Clang 18.1.5 with GNU-like command-line -- Detecting C compiler ABI info CMake Error: Running
> 
> '/usr/bin/ninja.exe' '-C' '/home/mesut/erofs/out/CMakeFiles/CMakeScratch/TryCompile-Z8WXCm' '-t' 'recompact'
> 
> failed with:
> 
> ninja: fatal: chdir to '/home/mesut/erofs/out/CMakeFiles/CMakeScratch/TryCompile-Z8WXCm' - No such file or directory
> 
> CMake Error: Running
> 
> '/usr/bin/ninja.exe' '-C' '/home/mesut/erofs/out/CMakeFiles/CMakeScratch/TryCompile-Z8WXCm' '-t' 'restat' 'build.ninja'
> 
> failed with:
> 
> ninja: fatal: chdir to '/home/mesut/erofs/out/CMakeFiles/CMakeScratch/TryCompile-Z8WXCm' - No such file or directory
> 
> CMake Error at /usr/share/cmake-3.28.3/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile): Failed to generate test project build system. Call Stack (most recent call first): /usr/share/cmake-3.28.3/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI) CMakeLists.txt:2 (project)
> 
> -- Configuring incomplete, errors occurred! ninja: error: loading 'build.ninja': The system cannot find the file specified.
> 
> ninja: Entering directory `./out' error
> 
> whats problem ?

Did you installed ninja from cygwin install program?

**Comment by seci20** [comment]
I found that the clang installation directory was faulty. When I installed it in the correct directory, it compiled without any problems.
