### ISSUE TITLE
broken Erofs with lzma,deflate i guess

### ISSUE THREAD

**Issue by amackpro** [sekaiacg/erofs-utils#26]
images get built successfully but when i try to mount it 
then this error shows up

mount command used 
**mount -t erofs -o loop vendor_a.img s**

mount: /mnt/c/Users/amack/Desktop/Repacktool/pack_output_vendor_a/s: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
       
       
commands used
### %~dp0bin\erofs\mkfs.erofs.exe -b4096 -zlzma,level=9 -T 1230768000 --mount-point=/%name% --file-contexts=%~dp1config\%name%\%name%_file_contexts --fs-config-file=%~dp1config\%name%\%name%_fs_config %~dp1pack_output_%name%/%name%.img %~dp1%name%

**Comment by amackpro** [comment]
> > -zlzma,level=9
> 
> I don’t have a windows environment, and the test passed under archlinux: Linux arch 6.9.3-zen1-1-zen
> 
> Please try using dump.erofs or extract.erofs, and if the extraction is successful, check if your kernel supports these compression formats.

i tried mounting on   5.15.146.1-microsoft-standard-WSL2

**Comment by sekaiacg** [comment]
> > > -zlzma,level=9
> > 
> > 
> > I don’t have a windows environment, and the test passed under archlinux: Linux arch 6.9.3-zen1-1-zen
> > Please try using dump.erofs or extract.erofs, and if the extraction is successful, check if your kernel supports these compression formats.
> 
> i tried mounting on 5.15.146.1-microsoft-standard-WSL2,
> 
> tried on 6.9.3 WSL kernel also , got same error
> 
> got same error when built in using WSL

When a mount error occurs, check the kernel log (dmesg)!

**Comment by sekaiacg** [comment]
Also, are extrace.erof and dump.erofs available?

**Comment by amackpro** [comment]
> Also, are extrace.erof and dump.erofs available?

file get extracted fine with 0 corruption with extract.erofs

**Comment by sekaiacg** [comment]
> > Also, are extrace.erof and dump.erofs available?
> 
> file get extracted fine with 0 corruption with extract.erofs

I think it's a kernel issue.
