### ISSUE TITLE
The build product does not contain extract.erofs, and the different between on extract.erofs and fsck.erofs --extrace

### ISSUE THREAD

**Issue by tcc0lin** [sekaiacg/erofs-utils#28]
Please **do not** send pull-requests or open new issues on Github.

Besides, the current erofs-utils repo is:
git://git.kernel.org/pub/scm/linux/kernel/git/xiang/erofs-utils.git

Github is not _the place_ for EROFS development, and some mirrors
are actually unofficial and not frequently monitored.

* Send bug reports and/or feedback to: linux-erofs@lists.ozlabs.org

**Comment by sekaiacg** [comment]
1. erofs-utils is open source software and is not restricted by the repository.
3. GitHub is very convenient, I like it very much.
