### ISSUE TITLE
making erofs img

### ISSUE THREAD

**Issue by stepik** [sekaiacg/erofs-utils#7]
Hello! Thank you for your great erofs-utils! Can I ask you a question? Why I can make erofs img with selinux file labels only on Android? I tried to make it on Ubuntu and wsl and it generate with blank selinux labels, can you make an advice: why it is blank and what linux I need to best use?

**Comment by sekaiacg** [comment]
Please execute: `./mkfs.erofs`
to get more help.

If you need to use selinux, please provide parameters: 
`--file-contexts=X specify a file contexts file to setup selinux labels`

**Comment by stepik** [comment]
Yes this works if I use arm version of mkfs.erofs on android, but not on a linux erofs because it's generate a blank selinux files in a img.

**Comment by sekaiacg** [comment]
> Yes this works if I use arm version of mkfs.erofs on android, but not on a linux erofs because it's generate a blank selinux files in a img.

I don't understand the problem, I will test it tomorrow.

**Comment by stepik** [comment]
*blank selinux labels

**Comment by stepik** [comment]
> I don't understand the problem, I will test it tomorrow.

My mistake. I downloaded the latest build and it works on wsl, I don't understand why it didn't work before. Sorry to bother you.

**Comment by sekaiacg** [comment]
> > I don't understand the problem, I will test it tomorrow.
> 
> My mistake. I downloaded the latest build and it works on wsl, I don't understand why it didn't work before. Sorry to bother you.

After testing, selabel is normal.
